services:
  - type: web
    name: api
    runtime: node
    rootDir: api
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 18
